### ISSUE TITLE
Speaker section picture layout errors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2016.fossasia.org#42] opened 2016-03-07 07:02 UTC
There is an issue with the pic layout. Anyone ideas?

![screenshot from 2016-03-07 15 01 40](https://cloud.githubusercontent.com/assets/1583873/13562640/9958dc18-e475-11e5-93f5-a8991ddef722.png)

**Comment by daminisatya** [comment] 2016-03-07 07:06
@mariobehling add every four images in a new div. This will resolve it.

**Comment by SilentFlame** [comment] 2016-03-09 18:06
I guess this issue has been resolved,
as I'm unable to reproduce the layout problem.
Have a look agian @mariobehling .
You can close it if you think its resolved.

**Comment by shubh1m** [comment] 2016-03-10 23:55
Hey @mariobehling. Created a PR at https://github.com/fossasia/2016.fossasia.org/pull/66. Have a look.

**Comment by shubh1m** [comment] 2016-03-11 00:19
I have also changed the height and width of the speaker images to 240*240 px . So, it would be relatively faster to load. All that needs to be done is to shrink all the images which can easily be handled via a python script if someone can proceed.

**Closed as completed** 2016-03-11 10:10 UTC

**Comment by shubh1m** [comment] 2016-03-11 23:43
@jig08 I think the issue is back again.
